# Generated by Django 2.2.4 on 2020-01-18 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='1st', max_length=10)),
                ('vehicleModel', models.CharField(max_length=20)),
                ('token', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceTravelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserAccount')),
            ],
        ),
    ]
