# Generated by Django 3.0.2 on 2020-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200118_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolPump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('rating', models.FloatField()),
                ('number', models.IntegerField()),
                ('GRating', models.FloatField()),
            ],
        ),
    ]
