# Generated by Django 2.2.4 on 2020-02-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_petrolpump'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolpump',
            name='bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='behavior',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='cashless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='sanity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='petrolpump',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
    ]
