# Generated by Django 2.2.4 on 2020-01-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('totalDistance', models.DecimalField(decimal_places=6, max_digits=10)),
                ('petrolLevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('petrolConsumed', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserAccount')),
            ],
        ),
    ]
