# Generated by Django 2.2.4 on 2020-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_currentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='petrolConsumed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='petrolLevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='totalDistance',
            field=models.FloatField(),
        ),
    ]
